version: '3'

services:
  development:
    image: mcr.microsoft.com/devcontainers/universal:2
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/workspaces:cached
      - data:/data

  frontend:
    build:
      context: ../frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env

  backend:
    build:
      context: ../backend
      dockerfile: .docker/Dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    env_file:
      - .env

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "${DEV_ETH_PORT:-8545}:8545"
    env_file:
      - .env
    volumes:
      - ganache-data:/data

  blockchain:
    build:
      context: ../blockchain
      dockerfile: .docker/Dockerfile
    ports:
      - "${BLOCKCHAIN_PORT:-7070}:7070"
    env_file:
      - .env

  contracts:
    build:
      context: ../contracts
      dockerfile: .docker/Dockerfile
    env_file:
      - .env

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "${IPFS_API_PORT:-5001}:5001"
      - "${IPFS_UI_PORT:-8080}:8080"
    volumes:
      - ipfs-data:/data/ipfs
    env_file:
      - .env

volumes:
  data:
  ganache-data:
  ipfs-data:
