version: '3'

services:
  development:
    image: mcr.microsoft.com/devcontainers/universal:2
    env_file:
      - .env # Ortam değişkenlerini .env dosyasından yükle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/workspaces:cached
      - data:/data

  frontend:
    build:
      context: ../frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env # Ortam değişkenlerini .env dosyasından yükle

  backend:
    build:
      context: ../backend
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env # Ortam değişkenlerini .env dosyasından yükle

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    env_file:
      - .env # Ortam değişkenlerini .env dosyasından yükle
    volumes:
      - ganache-data:/data

  blockchain:
    build:
      context: ../blockchain
      dockerfile: .docker/Dockerfile
    ports:
      - "6545:6545"
    env_file:
      - .env # Ortam değişkenlerini .env dosyasından yükle      

  contracts:
    build:
      context: ../contracts
      dockerfile: .docker/Dockerfile
    env_file:
      - .env # Ortam değişkenlerini .env dosyasından yükle

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs
    env_file:
      - .env # Ortam değişkenlerini .env dosyasından yükle

volumes:
  data:
  ganache-data:
  ipfs-data:
