version: '3.8'

services:

  development:
    image: mcr.microsoft.com/devcontainers/universal:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/workspaces:cached
      - data:/data

  frontend:
    build:
      context: ../frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ../backend
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"
      
  # contracts:
  #   build:
  #     context: ../contracts
  #     dockerfile: .docker/Dockerfile

  # blockchain:
  #   build:
  #     context: ../blockchain
  #     dockerfile: .docker/Dockerfile
  #   ports:
  #     - "8545:8545"

volumes:
  data:
